### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at 'Missing parent'

### ISSUE THREAD

**Issue by neon64** [oxalica/onedrive-fuse#1]
Hi! Looks like an awesome project. Alas, I've came across an issue first time when trying to mount the filesystem:

```
thread 'tokio-runtime-worker' panicked at 'Missing parent', /home/user/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/onedrive-fuse-0.2.1/src/vfs/inode.rs:488:42
stack backtrace:
   0:     0x55a49980cd40 - std::backtrace_rs::backtrace::libunwind::trace::h5903c95be80856c4
                               at /rustc/2f391da2e6ac73faa3570b79de239fd8c0edf1a9/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55a49980cd40 - std::backtrace_rs::backtrace::trace_unsynchronized::h555432bbdcb7786a
                               at /rustc/2f391da2e6ac73faa3570b79de239fd8c0edf1a9/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55a49980cd40 - std::sys_common::backtrace::_print_fmt::hfb8f9e630dd35428
                               at /rustc/2f391da2e6ac73faa3570b79de239fd8c0edf1a9/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55a49980cd40 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbddc953817c1b2bd
                               at /rustc/2f391da2e6ac73faa3570b79de239fd8c0edf1a9/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55a49983269c - core::fmt::write::h9a6d9c74526a6c1b
                               at /rustc/2f391da2e6ac73faa3570b79de239fd8c0edf1a9/library/core/src/fmt/mod.rs:1115:17
   5:     0x55a4998067b5 - std::io::Write::write_fmt::ha6fa498b5bcf987b
                               at /rustc/2f391da2e6ac73faa3570b79de239fd8c0edf1a9/library/std/src/io/mod.rs:1663:15
   6:     0x55a49980f0fb - std::sys_common::backtrace::_print::h60a9ce36084b984c
                               at /rustc/2f391da2e6ac73faa3570b79de239fd8c0edf1a9/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55a49980f0fb - std::sys_common::backtrace::print::h0284410b94411863
                               at /rustc/2f391da2e6ac73faa3570b79de239fd8c0edf1a9/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55a49980f0fb - std::panicking::default_hook::{{closure}}::h2b882c1f2d8a978f
                               at /rustc/2f391da2e6ac73faa3570b79de239fd8c0edf1a9/library/std/src/panicking.rs:208:50
   9:     0x55a49980ebd1 - std::panicking::default_hook::hf81fb6b58f1c3364
                               at /rustc/2f391da2e6ac73faa3570b79de239fd8c0edf1a9/library/std/src/panicking.rs:225:9
  10:     0x55a4994efd0e - onedrive_fuse::main::{{closure}}::{{closure}}::h2295821e1bcfea9d
  11:     0x55a49980f7e9 - std::panicking::rust_panic_with_hook::h4ddef44fa60cc4c7
                               at /rustc/2f391da2e6ac73faa3570b79de239fd8c0edf1a9/library/std/src/panicking.rs:626:17
  12:     0x55a49980f2a7 - std::panicking::begin_panic_handler::{{closure}}::h564f61b4b0976d00
                               at /rustc/2f391da2e6ac73faa3570b79de239fd8c0edf1a9/library/std/src/panicking.rs:519:13
  13:     0x55a49980d21c - std::sys_common::backtrace::__rust_end_short_backtrace::h7633444d01f53658
                               at /rustc/2f391da2e6ac73faa3570b79de239fd8c0edf1a9/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x55a49980f209 - rust_begin_unwind
                               at /rustc/2f391da2e6ac73faa3570b79de239fd8c0edf1a9/library/std/src/panicking.rs:515:5
  15:     0x55a49943e841 - core::panicking::panic_fmt::hcf5f6d96e1dd7099
                               at /rustc/2f391da2e6ac73faa3570b79de239fd8c0edf1a9/library/core/src/panicking.rs:92:14
  16:     0x55a49943e733 - core::option::expect_failed::h0a5d8f51a88056e8
                               at /rustc/2f391da2e6ac73faa3570b79de239fd8c0edf1a9/library/core/src/option.rs:1577:5
  17:     0x55a49955e89e - onedrive_fuse::vfs::inode::InodePool::sync_items::hcf0c7141b3533888
  18:     0x55a4994d67a0 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::haf94e486a03e3b58
  19:     0x55a49944b7d3 - tokio::runtime::task::harness::poll_future::hd6ab871335aef574
  20:     0x55a49945afb4 - tokio::runtime::task::harness::Harness<T,S>::poll::h8c11f9bc1f61732d
  21:     0x55a49979cf53 - std::thread::local::LocalKey<T>::with::h4c7461f572c2eae9
  22:     0x55a4997a2672 - tokio::runtime::thread_pool::worker::Context::run_task::hb4c1745810fae29b
  23:     0x55a4997a181c - tokio::runtime::thread_pool::worker::Context::run::h44ff5913b6be6b80
  24:     0x55a4997b7d13 - tokio::macros::scoped_tls::ScopedKey<T>::set::hd53ea5e49909f6b9
  25:     0x55a4997a12c1 - tokio::runtime::thread_pool::worker::run::hbbec9b49fdd45a79
  26:     0x55a4997a8b9e - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hcbcb2bad24f115a8
  27:     0x55a4997c1110 - tokio::runtime::task::harness::Harness<T,S>::poll::hccbde3f04b246388
  28:     0x55a4997a9cba - tokio::runtime::blocking::pool::Inner::run::h87cec103da1ed0ef
  29:     0x55a4997b2a0f - std::sys_common::backtrace::__rust_begin_short_backtrace::hd9e23719666eecfa
  30:     0x55a4997b33a1 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h03d6374f1f4141aa
  31:     0x55a4998153a7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc38d4ae20ff37ccc
                               at /rustc/2f391da2e6ac73faa3570b79de239fd8c0edf1a9/library/alloc/src/boxed.rs:1572:9
  32:     0x55a4998153a7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h87bdfb564d1ef742
                               at /rustc/2f391da2e6ac73faa3570b79de239fd8c0edf1a9/library/alloc/src/boxed.rs:1572:9
  33:     0x55a4998153a7 - std::sys::unix::thread::Thread::new::thread_start::h051554aec0a423e5
                               at /rustc/2f391da2e6ac73faa3570b79de239fd8c0edf1a9/library/std/src/sys/unix/thread.rs:74:17
  34:     0x7f295441f259 - start_thread
  35:     0x7f29541fb5e3 - __GI___clone
  36:                0x0 - <unknown>
```

I just installed with `cargo install`, but if I've got time I'll try and log the particular inode which causes this issue...

**Comment by oxalica** [comment]
The panic should be fixed in 0.2.2, and a warning will be printed for the problematic file with `Skip item ... with unexpected new parent: ...`.
Could you please reinstall and try again and see if everything works now?
If you see the warning, could you please check if that file or directory actually exist and verify if it's in the expected path in mounted directory?

**Comment by neon64** [comment]
Thanks! Have installed 0.2.2 and that seems to have done the trick.
I've posted the (slightly redacted, just in case certain IDs etc... are sensitive) log lines below, it appears to be items related to certain OneDrive notebooks... I don't care about them being synced though

```
[2021-08-09T05:46:45Z WARN  onedrive_fuse::vfs::inode] Skip item ItemId("***") with unexpected new parent: DriveItem { audio: None, content: None, c_tag: Some(Tag("***")), deleted: None, description: None, file: None, file_system_info: Some(Object({"createdDateTime": String("2019-12-22T03:23:53.39Z"), "lastModifiedDateTime": String("2019-12-22T03:23:53.54Z")})), folder: None, image: None, location: None, package: None, photo: None, publication: None, remote_item: None, root: None, search_result: None, shared: None, sharepoint_ids: None, size: Some(2192), special_folder: None, video: None, web_dav_url: None, children: None, created_by_user: None, last_modified_by_user: None, permissions: None, thumbnails: None, versions: None, id: Some(ItemId("***")), created_by: None, created_date_time: None, e_tag: None, last_modified_by: None, last_modified_date_time: None, name: Some("OneNote_DeletedPages.one"), parent_reference: Some(Object({"driveId": String("***"), "driveType": String("personal"), "id": String("***"), "name": String("OneNote_RecycleBin"), "path": String("/drive/root:/Documents/Notebook/OneNote_RecycleBin")})), web_url: None, download_url: None }
[2021-08-09T05:46:45Z WARN  onedrive_fuse::vfs::inode] Skip item ItemId("***") with unexpected new parent: DriveItem { audio: None, content: None, c_tag: Some(Tag("***")), deleted: None, description: None, file: None, file_system_info: Some(Object({"createdDateTime": String("2019-07-30T10:03:41.7Z"), "lastModifiedDateTime": String("2019-12-22T03:23:58.76Z")})), folder: None, image: None, location: None, package: None, photo: None, publication: None, remote_item: None, root: None, search_result: None, shared: None, sharepoint_ids: None, size: Some(8923), special_folder: None, video: None, web_dav_url: None, children: None, created_by_user: None, last_modified_by_user: None, permissions: None, thumbnails: None, versions: None, id: Some(ItemId("***")), created_by: None, created_date_time: None, e_tag: None, last_modified_by: None, last_modified_date_time: None, name: Some("New Section 1.one"), parent_reference: Some(Object({"driveId": String("***"), "driveType": String("personal"), "id": String("***"), "name": String("OneNote_RecycleBin"), "path": String("/drive/root:/Documents/Notebook/OneNote_RecycleBin")})), web_url: None, download_url: None }
[2021-08-09T05:46:45Z WARN  onedrive_fuse::vfs::inode] Skip item ItemId("***") with unexpected new parent: DriveItem { audio: None, content: None, c_tag: Some(Tag("***")), deleted: None, description: None, file: None, file_system_info: Some(Object({"createdDateTime": String("2019-12-22T03:23:52.126Z"), "lastModifiedDateTime": String("2019-12-22T03:24:00.826Z")})), folder: None, image: None, location: None, package: None, photo: None, publication: None, remote_item: None, root: None, search_result: None, shared: None, sharepoint_ids: None, size: Some(2438), special_folder: None, video: None, web_dav_url: None, children: None, created_by_user: None, last_modified_by_user: None, permissions: None, thumbnails: None, versions: None, id: Some(ItemId("***")), created_by: None, created_date_time: None, e_tag: None, last_modified_by: None, last_modified_date_time: None, name: Some("Open Notebook.onetoc2"), parent_reference: Some(Object({"driveId": String("***"), "driveType": String("personal"), "id": String("***"), "name": String("OneNote_RecycleBin"), "path": String("/drive/root:/Documents/Notebook/OneNote_RecycleBin")})), web_url: None, download_url: None }
```

**Comment by oxalica** [comment]
Thanks for testing. 

> it appears to be items related to certain OneDrive notebooks

OneNote files (`*.one`, or maybe more) have weird hierarchy reported by API. They are files but have some children, making them also like a directory.
Currently we explicit ignore this deep hierarchy and treat these files just as regular files in some other part of code.
Maybe you can simply ignore the warnings above.
